# Generated by Django 5.0.2 on 2024-03-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_item_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
