# Generated by Django 5.0.2 on 2024-04-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_user_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
