# Generated by Django 5.0.2 on 2024-05-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_bookingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
